First 3 levels
sceletoniK/WeeBee-test pull request #1
Opened 2023-03-18 19:10 UTC by sceletoniK

2023-03-19 14:01 UTC, crutch12 commented
@IvanKoigerov теперь это твой крест

2023-03-20 20:24 UTC, IvanKoigerov reviewed
Нормально написал,
Но только вот var это устаревший формат, так что забудь о нем) 
https://learn.javascript.ru/var

Исправь замечания, а потом тегай меня через `@` или напиши в телеге
https://t.me/An1meBoy
Так же можешь обращаться ко мне с вопросами

2023-03-20 20:24 UTC, IvanKoigerov commented on style/style.css
> +    background: #F1F1F1!important;
`!important`
лучше никогда не юзать, только в самых редких случаях, это явно не из этих случаев)
Да и писать стили для тегов лучше не надо, 
Используй классы

2023-03-20 20:24 UTC, IvanKoigerov commented on style/style.css
> +.post, .detail_post, .profile, .timer, .map{
будто бы лучше прост класс создать и навешивать несколько классов

2023-03-20 20:24 UTC, IvanKoigerov commented on style/style.css
> +a {
лучше стили для тегов на классы перепиши

2023-03-20 20:24 UTC, IvanKoigerov commented on style/style.css
> +    vertical-align: 0!important;
будто можно без этого обойтись

2023-03-20 20:24 UTC, IvanKoigerov commented on index.html
> +            <path fill-rule="evenodd" clip-rule="evenodd" d="M5.68634 0.608257C8.41347 0.443564 11.3102 2.03315 11.7406 5.55589C11.7709 5.80397 11.7892 6.03466 11.7921 6.24238C11.8078 7.36434 11.4512
вставляй svg через ссылки, неудобно смотреть html

2023-03-20 20:24 UTC, IvanKoigerov commented on blocks/profile.html
> +        <div class="d-flex d-row justify-content-between align-items-center w-100 my-1" style="min-height: 37px;">
не юзай  атрибут `style`, лучше в стилях прописывать

2023-03-20 20:24 UTC, IvanKoigerov commented on blocks/profile.html
> +        <textarea cols="40" rows="3" class="form-control mx-2 my-3" style="width: 85%!important; min-height: 88px; resize: none;"  placeholder="Enter your message..."></textarea>
не юзай  атрибут `style`, лучше в стилях прописывать

2023-03-20 20:24 UTC, IvanKoigerov commented on script/script.js
Название файла ни о чем не говорит

2023-03-20 20:24 UTC, IvanKoigerov commented on script/script.js
> +routes["#timer"] = "blocks/timer.html"
почему не сразу в объект закидываешь?

2023-03-20 20:24 UTC, IvanKoigerov commented on script/script.js
> +            timePrinter = null
а почему не в `if (timePrinter != null)`?

2023-03-20 20:24 UTC, IvanKoigerov commented on script/script.js
> +        case("blocks/map.html"):
"blocks/map.html" можешь не ручками прописывать

2023-03-20 20:24 UTC, IvanKoigerov commented on script/script.js
> +            e.stopPropagation();
зачем если ниже юзаешь `e.preventDefault();`

2023-03-20 20:24 UTC, IvanKoigerov commented on script/script.js
> +        item.addEventListener('click', (e) => {
`click` 
не используй клик, ссылка должна оставаться ссылкой, вешай обработчик на саму ссылку

2023-03-20 20:24 UTC, IvanKoigerov commented on script/timer.js
> +var timePrinter = null
почему юзаешь `null` а не `undefined`

2023-03-20 20:24 UTC, IvanKoigerov commented on script/timer.js
> +    var timestring = '' + Math.floor(hour/10) + (hour % 10) + ':' + Math.floor(min/10) + (min % 10) + ':' + Math.floor(sec/10) + (sec % 10)
мог не париться и юзать `

2023-03-20 20:24 UTC, IvanKoigerov commented on style/style.css
> +    width: 70%;
Я бы лучше так не делал
может тут норм работает, но лучше % не юзать кроме 50 и 100
можно спокойно споткнуться об это

2023-03-20 20:24 UTC, IvanKoigerov commented on script/timer.js
> +var timePrinter = null
не вижу особо смысла в этой переменной тут (в этом файле)
и в timerP

2023-03-20 20:24 UTC, IvanKoigerov commented on script/script.js
> +            timePrinter = null
лучше юзать строгое равенство `===` или не равенство `!==`
например `== null` - это `null` и `undefined`

Ну а в данном примере я бы просто `if(timePrinter)` просто писал

2023-03-20 20:26 UTC, IvanKoigerov commented
Ещё один совет, коммиты пиши как-то так
fix: исправлен timer
feat: добавлена адаптивность

Привыкай сразу как у нас пишут)

2023-03-22 15:43 UTC, sceletoniK commented
@IvanKoigerov вроде все поправил

2023-03-22 16:41 UTC, IvanKoigerov reviewed
Норм, чуть-чуть подфикси и закончим с этим заданием)

2023-03-22 16:41 UTC, IvanKoigerov commented on index.html
> +          <img src="source/n2.svg" class="svg_img">
Есть такая штука как 
```
<svg>
   <use href='/svg.svg'/>
</svg>```

я бы юзал ее, а не img

2023-03-22 16:41 UTC, IvanKoigerov commented on index.html
> +          <img src="source/n2.svg" class="svg_img">
Но уже можешь не переделывать

2023-03-22 16:41 UTC, IvanKoigerov commented on index.html
> +            <img src="source/h1.svg" class="me-3">
`h1.svg`
на будущее лучше так не называть картинки, лучше называть по тому что там нарисовано или по сущности, где используется
Иначе не понятно что это за картинка тут используется

ща можешь не переделывать

2023-03-22 16:41 UTC, IvanKoigerov commented on script/router.js
> +let main = undefined
`let main;` - это уже `undefined`

2023-03-22 16:41 UTC, IvanKoigerov commented on blocks/profile.html
> +          <a href="" class="a">
можно же без `href=""` `<а/>` юзать

2023-03-22 16:41 UTC, IvanKoigerov commented on blocks/profile.html
> +        <form class="d-flex flex-column align-items-center">
зачем тебе тут form?

2023-03-22 16:41 UTC, IvanKoigerov commented on script/map.js
> +    var geolocation = ymaps.geolocation,
var

2023-03-22 16:41 UTC, IvanKoigerov commented on style/style.css
> +.a {
не называй классы по названию тега, не всегда можно понять что это

2023-03-22 16:41 UTC, IvanKoigerov commented on style/style.css
> +.a {
кроме кнопки и textarea
в остальных местах лучше называть зачем оно используется
p - text, typography
a - link
div - обертка wrapper

2023-03-22 16:41 UTC, IvanKoigerov commented on index.html
> +  <body class="container-fluid d-flex vh-100 flex-column body" onload="Load()">
лучше никогда не навешивай стили на сам body, лучше юзай дочерний div

2023-03-22 16:41 UTC, IvanKoigerov commented on index.html
> +  <body class="container-fluid d-flex vh-100 flex-column body" onload="Load()">
`onload="Load()"`
Я бы привязался к ивенту в js, чем в html юзать js

2023-03-22 17:04 UTC, IvanKoigerov commented on script/router.js
> +            timePrinter = null
Я бы все таки закинул в if, чтобы лишний раз не переопределять переменную и clearInterval не вызывать

ещё выбери что юзаешь undefined или null

2023-03-22 17:05 UTC, sceletoniK commented on blocks/profile.html
> +        <form class="d-flex flex-column align-items-center">
По смыслу тут поле и кнопка submit своеобразная, ну я и обернул в бесполезную но форму

2023-03-22 18:45 UTC, sceletoniK commented on blocks/profile.html
> +        <form class="d-flex flex-column align-items-center">
Ведь тут форма подразумевается, разве не так ?

2023-03-26 08:04 UTC, IvanKoigerov commented on blocks/profile.html
> +        <form class="d-flex flex-column align-items-center">
ну по сети наверное да

2023-03-26 11:20 UTC, sceletoniK commented
@IvanKoigerov, все кроме формы исправил

2023-03-26 16:33 UTC, IvanKoigerov commented on style/style.css
> +.a {
все ещё название класса `a`
`body`
`p_text`

2023-03-26 16:33 UTC, IvanKoigerov commented on style/style.css
> +    min-height: 37px;
`min-height` как-то не похоже на margin))
и называй классы по сущностям, не понятно что за `box_margin` и для чего он

2023-03-26 16:33 UTC, IvanKoigerov commented on style/style.css
> +.profile .btn{
есть ли тут смысл во вложенности?
`.profile .textarea` это тож

2023-03-26 16:33 UTC, IvanKoigerov commented on style/style.css
> +.active{
active что?
Не понятно из название что это такое

2023-03-26 16:35 UTC, IvanKoigerov commented on style/style.css
> +.active{
@crutch12 можешь смотреть

2023-03-26 16:35 UTC, IvanKoigerov commented
@crutch12 можешь смотреть

2023-04-13 20:27 UTC, crutch12 requested changes

2023-04-13 20:27 UTC, crutch12 commented on script/router.js
> +window.onload = Load
Не используй никогда обработчики такого вида
Используй `addEventListener(...)`
Потому что в текущий кто угодно может закинуть свой обработчик и твой перестанет работать

2023-04-13 20:27 UTC, crutch12 commented on script/router.js
> +            links[2].classList.add("active")
ищи ссылку через href
представь, что у тебя 100 страничек

2023-04-13 20:27 UTC, crutch12 commented on script/router.js
> +    window.addEventListener("hashchange", changePage)
я не понял, где ты меняешь хэш, но в любом случае нафиг
делай через history api переходы

2023-04-13 20:27 UTC, crutch12 commented on script/timer.js
> +    time++;
setInterval не гарантирует, что пройдёт ровно 1000мс, поэтому с каждым новым тиком ты накапливаешь ошибку
подумай, чё с этим можно сделать

2023-04-13 20:27 UTC, crutch12 commented on source/post.jpg
❤️

2023-05-25 15:21 UTC, crutch12 commented
Ну ладно, не в этот раз, расходимся

2023-06-16 17:05 UTC, merged